apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: my-app-prod
namePrefix: prod-

commonLabels:
  foo: bar


configMapGenerator:
  - name: app-config
    literals:
      - username=prod-user-demo

secretGenerator:
  - name: credentials
    type: Opaque
    literals:
      - password=foo
  - name: certs
    files:
      - assets/ca.pem



patchesStrategicMerge:
- deployment_replicas.yaml
- deployment_env.yaml
- deployment_volume.yaml

