apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: my-app-prod
namePrefix: prod-

commonLabels:
  foo: bar

patchesStrategicMerge:
  - deployment_replicas.yaml
